"""Build js/program.js from Jeff Nippard's Ultimate PPL 6x spreadsheet (.xlsx download of the Google Sheet).
Usage: python3 tools/extract_program.py path/to/sheet.xlsx > js/program.js
Excel turns ranges like "3-4" or "8-9" into dates; those are converted back to "M-D"."""
import sys, re, json, datetime, openpyxl

DAY_IDS={"Push #1":"push1","Pull #1":"pull1","Legs #1":"legs1","Push #2":"push2","Pull #2":"pull2","Legs #2":"legs2"}

def val(c):
    v=c.value
    if v is None: return ""
    if isinstance(v,datetime.datetime): return f"{v.month}-{v.day}"
    if isinstance(v,float) and v.is_integer(): v=int(v)
    return re.sub(r"\s+"," ",str(v)).strip()

def link(c):
    t=c.hyperlink.target if c.hyperlink else None
    return t.strip() if t else ""

def opt(c):
    n=val(c)
    return None if n in ("","N/A") else {"n":n,"v":link(c)}

def phase(ws):
    title=""; weeks=[]; week=None; day=None; pending_note=""
    for r in range(1,ws.max_row+1):
        a=val(ws.cell(r,1)); b=val(ws.cell(r,2))
        if a.startswith("Phase "): title=a; continue
        if "DELOAD" in a.upper(): pending_note=a; continue
        m=re.match(r"Week (\d+)$",a)
        if m:
            week={"n":int(m.group(1)),"note":pending_note,"days":[]}; weeks.append(week); pending_note=""; continue
        if a in DAY_IDS:
            day={"id":DAY_IDS[a],"name":a,"ex":[]}; week["days"].append(day)
        if a.startswith("Mandatory Rest"): day=None; continue
        if day is not None and b and b!="Exercise":
            e={"n":b,"v":link(ws.cell(r,2)),"wu":val(ws.cell(r,3)),"s":val(ws.cell(r,4)),"r":val(ws.cell(r,5)),
               "rpe":val(ws.cell(r,7)),"rest":val(ws.cell(r,8)),"note":val(ws.cell(r,11))}
            subs=[x for x in (opt(ws.cell(r,9)),opt(ws.cell(r,10))) if x]
            if subs: e["subs"]=subs
            day["ex"].append(e)
    m=re.match(r"Phase (\d+) - (.*?) \((.*)\)",title)
    return {"n":int(m.group(1)),"name":m.group(2),"desc":m.group(3),"weeks":weeks}

wb=openpyxl.load_workbook(sys.argv[1])
phases=[phase(ws) for ws in wb.worksheets if re.search(r"Phase \d",ws.title)]
for p in phases:
    for w in p["weeks"]:
        assert [d["id"] for d in w["days"]]==list(DAY_IDS.values()),(p["n"],w["n"])
        for d in w["days"]:
            for e in d["ex"]:
                if not e["v"]: print(f"warning: no video for {e['n']} (P{p['n']} W{w['n']} {d['name']})",file=sys.stderr)
print("/* Generated by tools/extract_program.py from Jeff Nippard's Ultimate PPL 6x spreadsheet. Do not edit by hand.")
print("   PROGRAM.phases[].weeks[].days[].ex[] = { n, v (video), wu, s, r, rpe, rest, note, subs: [{ n, v }] } */")
print("export const PROGRAM="+json.dumps({"phases":phases},ensure_ascii=False,separators=(",",":"))+";")
